title: DevOps Tutorial
description: Best tutorial blog for learning DevOps
google_analytics: UA-199918385-1

plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

# To inclue default layout for all
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
